version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor: node/default
    steps:
      - run:
          name: Swap node versions
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install v12.19.0
            nvm alias default 12.19.0

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - checkout
      - node/install-packages:
          cache-path: ~/bjj/node_modules
          override-ci-command: yarn
      - run: yarn test
workflows:
  test_my_app:
    jobs:
      - test
